# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.cache/wt [current_project]
set_property parent.project_path /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/coe/conv1_bm_ram.coe
add_files /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/coe/conv2_bm_ram.coe
add_files /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/coe/ip1_bm_ram.coe
read_verilog -library xil_defaultlib -sv {
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/acc_addr.sv
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/vector_muladd.sv
}
read_verilog -library xil_defaultlib {
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/addr2.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/addr4.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/bit_trunc.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/bn_bias_relu.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/busm2n.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/controller_v2.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/controller_v2_a.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/try6/TIDENet/accdnn/build/src/conv1_layer.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/try6/TIDENet/accdnn/build/src/conv2_layer.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/ddr_read_delay.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/delay.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/verilog/interlayer_sync_fifo.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/try6/TIDENet/accdnn/build/src/ip1_layer.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/multiplier.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/try6/TIDENet/accdnn/build/src/pool1_layer.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/try6/TIDENet/accdnn/build/src/pool2_layer.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/vivado_prj/lenet1/lenet1.srcs/sources_1/imports/tidenet/vivado_prj/project_2/project_2.srcs/sources_1/imports/verilog/vector_max.v
  /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/imports/tidenet/try6/TIDENet/accdnn/build/src/model.v
}
read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv1_rm_ram/conv1_rm_ram.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv1_rm_ram/conv1_rm_ram_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv1_wm_ram/conv1_wm_ram.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv1_wm_ram/conv1_wm_ram_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv1_bm_ram/conv1_bm_ram.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv1_bm_ram/conv1_bm_ram_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/pool1_rm_ram/pool1_rm_ram.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/pool1_rm_ram/pool1_rm_ram_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv2_rm_ram/conv2_rm_ram.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv2_rm_ram/conv2_rm_ram_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv2_wm_ram/conv2_wm_ram.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv2_wm_ram/conv2_wm_ram_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv2_bm_ram/conv2_bm_ram.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/conv2_bm_ram/conv2_bm_ram_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/pool2_rm_ram/pool2_rm_ram.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/pool2_rm_ram/pool2_rm_ram_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/ip1_rm_ram/ip1_rm_ram.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/ip1_rm_ram/ip1_rm_ram_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/ip1_wm_ram/ip1_wm_ram.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/ip1_wm_ram/ip1_wm_ram_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/ip1_bm_ram/ip1_bm_ram.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/ip1_bm_ram/ip1_bm_ram_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/mul16_unsigned/mul16_unsigned.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/mul16_unsigned/mul16_unsigned_ooc.xdc]

read_ip -quiet /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/mul16x16_signed/mul16x16_signed.xci
set_property used_in_implementation false [get_files -all /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/sources_1/ip/mul16x16_signed/mul16x16_signed_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/constrs_1/imports/timing/dma_timing.xdc
set_property used_in_implementation false [get_files /home/mm4uz/Desktop/research/tidenet/try6/lenet1_minimal/lenet1_minimal.srcs/constrs_1/imports/timing/dma_timing.xdc]


synth_design -top model -part xc7vx485tffg1761-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef model.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file model_utilization_synth.rpt -pb model_utilization_synth.pb"
