# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mm4uz/Desktop/research/tidenet/try6/TIDENet/accdnn/build/ips_prj/ips_prj.srcs/sources_1/ip/conv2_rm_ram/conv2_rm_ram.xci
# IP: The module: 'conv2_rm_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mm4uz/Desktop/research/tidenet/try6/TIDENet/accdnn/build/ips_prj/ips_prj.srcs/sources_1/ip/conv2_rm_ram/conv2_rm_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv2_rm_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/mm4uz/Desktop/research/tidenet/try6/TIDENet/accdnn/build/ips_prj/ips_prj.srcs/sources_1/ip/conv2_rm_ram/conv2_rm_ram.xci
# IP: The module: 'conv2_rm_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mm4uz/Desktop/research/tidenet/try6/TIDENet/accdnn/build/ips_prj/ips_prj.srcs/sources_1/ip/conv2_rm_ram/conv2_rm_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv2_rm_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
