# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mm4uz/Desktop/research/tidenet/try6/TIDENet/accdnn/build/ips_prj/ips_prj.srcs/sources_1/ip/mul16_unsigned/mul16_unsigned.xci
# IP: The module: 'mul16_unsigned' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mm4uz/Desktop/research/tidenet/try6/TIDENet/accdnn/build/ips_prj/ips_prj.srcs/sources_1/ip/mul16_unsigned/mul16_unsigned_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul16_unsigned'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/mm4uz/Desktop/research/tidenet/try6/TIDENet/accdnn/build/ips_prj/ips_prj.srcs/sources_1/ip/mul16_unsigned/mul16_unsigned.xci
# IP: The module: 'mul16_unsigned' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mm4uz/Desktop/research/tidenet/try6/TIDENet/accdnn/build/ips_prj/ips_prj.srcs/sources_1/ip/mul16_unsigned/mul16_unsigned_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul16_unsigned'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
