./lib/verilog/delay.v
./lib/verilog/addr2.v
./lib/verilog/multiplier.v
./lib/verilog/vector_max.v
./lib/verilog/addr3.v
./lib/verilog/ddr_read_delay.v
./lib/verilog/addr4.v
./lib/verilog/bit_trunc.v
./lib/verilog/busm2n.v
./lib/verilog/bn_bias_relu.v
./lib/verilog/controller_v2.v
./lib/verilog/acc_addr.sv
./lib/verilog/vector_muladd.sv
./lib/verilog/controller_v2_a.v
./build/src/pool3_layer.v
./build/src/pool1_layer.v
./build/src/pool2_layer.v
./build/src/model.v
./build/src/conv3_layer.v
./build/src/conv1_layer.v
./build/src/conv2_layer.v
./build/src/ip1_layer.v
./build/src/ip2_layer.v
