# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jmz8rm/tidenet/sim/lenet1_minimal.srcs/sources_1/ip/conv2_bm_ram/conv2_bm_ram.xci
# IP: The module: 'conv2_bm_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jmz8rm/tidenet/sim/lenet1_minimal.srcs/sources_1/ip/conv2_bm_ram/conv2_bm_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv2_bm_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/jmz8rm/tidenet/sim/lenet1_minimal.srcs/sources_1/ip/conv2_bm_ram/conv2_bm_ram.xci
# IP: The module: 'conv2_bm_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jmz8rm/tidenet/sim/lenet1_minimal.srcs/sources_1/ip/conv2_bm_ram/conv2_bm_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv2_bm_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
